config/routes.rb
Logorator::Application.routes.draw do
  resources :logos
  get 'logo/:name' => 'logos#generate'
  

end

app/models/logo.rb
class Logo

  require 'RMagick'
  include Magick

  def self.test
     img = Image.new(40, 40) { self.background_color = 'red' }
     text = Magick::Draw.new
     
     gc = Magick::Draw.new
     gc.gravity = Magick::CenterGravity
     gc.pointsize = 23
     gc.stroke = 'none'
     gc.fill = '#ffffff'
     gc.annotate(img, 0, 0, 0, 4, "FB")
     img.write('logo.jpg')
  end
  
  def self.logotify(company_name)
    points = []
    score = [] 
    company_name.split(//).each_with_index do |letter, index|
      point = 0
      point += 5 if index == 0
      if Logo.con?(letter)
        point += 1 
        point += 2 if Logo.previous_letter_is_a_voy?(company_name, index-1)
        point += 1 if Logo.previous_letter_is_a_voy?(company_name, index-1) && Logo.previous_letter_is_a_voy?(company_name, index-2)
      end
      point += 2 if Logo.voy?(letter)
      point += 3 if Logo.last_letter?(company_name, index)
      score << {letter => point} 
    end
     Logo.scorify(score)
  end
  
  def self.scorify(scores)
    company_scores = scores
    scores = scores.map { |x| x.values[0].to_i; }
    gap = 0
    resultat = []
    previous_index = 0
    3.times do |i|
      max_index = scores.index(scores.max) #0 #5 #3
      gap += 1 if i == 1
      resultat << max_index + gap
      previous_index = max_index
      scores.delete_at(max_index)
    end
    string = ""
    resultat.sort.each do |i|
      string += company_scores[i].keys[0]
    end
    string
  end
  
  def self.last_letter?(company_name, index)
    index == company_name.size - 1
  end
  
  def self.voy?(letter)
    ["a", "e", "i", "o", "u", "y"].include?(letter)
  end
  
  def self.con?(letter)
    !["a", "e", "i", "o", "u", "y"].include?(letter)
  end
  
  def self.voy?(letter)
    ["a", "e", "i", "o", "u", "y"].include?(letter)
  end
  
  def self.previous_letter_is_a_voy?(name, index)
    name[index] && Logo.voy?(name[index])
  end
  
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/logos_controller.rb
class LogosController < ApplicationController
  before_action :set_logo, only: [:show, :edit, :update, :destroy]
  
  def generate
    p params
    
    Logo.test
     
     
     
    render :text => params[:name]
  end
  
  # GET /logos
  # GET /logos.json
  def index
    @logos = Logo.all
  end

  # GET /logos/1
  # GET /logos/1.json
  def show
  end

  # GET /logos/new
  def new
    @logo = Logo.new
  end

  # GET /logos/1/edit
  def edit
  end

  # POST /logos
  # POST /logos.json
  def create
    @logo = Logo.new(logo_params)

    respond_to do |format|
      if @logo.save
        format.html { redirect_to @logo, notice: 'Logo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @logo }
      else
        format.html { render action: 'new' }
        format.json { render json: @logo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logos/1
  # PATCH/PUT /logos/1.json
  def update
    respond_to do |format|
      if @logo.update(logo_params)
        format.html { redirect_to @logo, notice: 'Logo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @logo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logos/1
  # DELETE /logos/1.json
  def destroy
    @logo.destroy
    respond_to do |format|
      format.html { redirect_to logos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_logo
      @logo = Logo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def logo_params
      params.require(:logo).permit(:abbreviation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logos_helper.rb
module LogosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Logorator</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/logos/_form.html.erb
<%= form_for(@logo) do |f| %>
  <% if @logo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@logo.errors.count, "error") %> prohibited this logo from being saved:</h2>

      <ul>
      <% @logo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :abbreviation %><br>
    <%= f.text_field :abbreviation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logos/edit.html.erb
<h1>Editing logo</h1>

<%= render 'form' %>

<%= link_to 'Show', @logo %> |
<%= link_to 'Back', logos_path %>

app/views/logos/index.html.erb
<h1>Listing logos</h1>

<table>
  <thead>
    <tr>
      <th>Abbreviation</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @logos.each do |logo| %>
      <tr>
        <td><%= logo.abbreviation %></td>
        <td><%= link_to 'Show', logo %></td>
        <td><%= link_to 'Edit', edit_logo_path(logo) %></td>
        <td><%= link_to 'Destroy', logo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Logo', new_logo_path %>

app/views/logos/new.html.erb
<h1>New logo</h1>

<%= render 'form' %>

<%= link_to 'Back', logos_path %>

app/views/logos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Abbreviation:</strong>
  <%= @logo.abbreviation %>
</p>

<%= link_to 'Edit', edit_logo_path(@logo) %> |
<%= link_to 'Back', logos_path %>